// Each book points to its own text content file.
const books = [
  {
    id: "bishop-deep-learning-2024",
    title: "深度学习：基础与概念",
    originalTitle: "Deep Learning: Foundations and Concepts",
    author: "Christopher M. Bishop · Hugh Bishop",
    year: "2024",
    description: "《深度学习：基础与概念》中文译文",
    legacyPageChapter: "01",
    referenceIndex: "books/bishop-deep-learning-2024/reference-index.json",
    offlineImages: "books/bishop-deep-learning-2024/offline-images.json",
    chapters: [
      { id: "frontmatter", number: "", title: "封面与出版信息", content: "books/bishop-deep-learning-2024/frontmatter.json" },
      { id: "00", number: "序", title: "前言", content: "books/bishop-deep-learning-2024/chapter-00.json" },
      { id: "contents", number: "", title: "原书目录", content: "books/bishop-deep-learning-2024/contents.json" },
      { id: "01", number: "1", title: "深度学习革命", content: "books/bishop-deep-learning-2024/chapter-01.json" },
      { id: "02", number: "2", title: "概率", content: "books/bishop-deep-learning-2024/chapter-02.json" },
      { id: "03", number: "3", title: "标准分布", content: "books/bishop-deep-learning-2024/chapter-03.json" },
      { id: "04", number: "4", title: "单层网络：回归", content: "books/bishop-deep-learning-2024/chapter-04.json" },
      { id: "05", number: "5", title: "单层网络：分类", content: "books/bishop-deep-learning-2024/chapter-05.json" },
      { id: "06", number: "6", title: "深层神经网络", content: "books/bishop-deep-learning-2024/chapter-06.json" },
      { id: "07", number: "7", title: "梯度下降", content: "books/bishop-deep-learning-2024/chapter-07.json" },
      { id: "08", number: "8", title: "反向传播", content: "books/bishop-deep-learning-2024/chapter-08.json" },
      { id: "09", number: "9", title: "正则化", content: "books/bishop-deep-learning-2024/chapter-09.json" },
      { id: "10", number: "10", title: "卷积网络", content: "books/bishop-deep-learning-2024/chapter-10.json" },
      { id: "11", number: "11", title: "结构化分布", content: "books/bishop-deep-learning-2024/chapter-11.json" },
      { id: "12", number: "12", title: "Transformer", content: "books/bishop-deep-learning-2024/chapter-12.json" },
      { id: "13", number: "13", title: "图神经网络", content: "books/bishop-deep-learning-2024/chapter-13.json" },
      { id: "14", number: "14", title: "采样", content: "books/bishop-deep-learning-2024/chapter-14.json" },
      { id: "15", number: "15", title: "离散潜变量", content: "books/bishop-deep-learning-2024/chapter-15.json" },
      { id: "16", number: "16", title: "连续潜变量", content: "books/bishop-deep-learning-2024/chapter-16.json" },
      { id: "17", number: "17", title: "生成对抗网络", content: "books/bishop-deep-learning-2024/chapter-17.json" },
      { id: "18", number: "18", title: "归一化流", content: "books/bishop-deep-learning-2024/chapter-18.json" },
      { id: "19", number: "19", title: "自编码器", content: "books/bishop-deep-learning-2024/chapter-19.json" },
      { id: "20", number: "20", title: "扩散模型", content: "books/bishop-deep-learning-2024/chapter-20.json" },
      { id: "A", number: "附录 A", title: "线性代数", content: "books/bishop-deep-learning-2024/appendix-a.json" },
      { id: "B", number: "附录 B", title: "变分法", content: "books/bishop-deep-learning-2024/appendix-b.json" },
      { id: "C", number: "附录 C", title: "拉格朗日乘子", content: "books/bishop-deep-learning-2024/appendix-c.json" },
      { id: "bibliography", number: "", title: "参考文献", content: "books/bishop-deep-learning-2024/bibliography.json" },
      { id: "index", number: "", title: "索引", content: "books/bishop-deep-learning-2024/index.json" },
    ],
  },
  {
    id: "shannon-mathematical-theory-1948",
    title: "通信的数学理论",
    originalTitle: "A Mathematical Theory of Communication",
    author: "C. E. Shannon",
    year: "1948",
    description: "引言、五篇正文与七个附录的完整中文译文",
    chapters: [
      { id: "00", number: "序", title: "引言", content: "books/shannon-mathematical-theory-1948/chapter-00.json" },
      { id: "01", number: "I", title: "无噪离散系统", content: "books/shannon-mathematical-theory-1948/chapter-01.json" },
      { id: "02", number: "II", title: "有噪离散信道", content: "books/shannon-mathematical-theory-1948/chapter-02.json" },
      { id: "a1-a4", number: "附录", title: "1—4", content: "books/shannon-mathematical-theory-1948/chapter-a1-a4.json" },
      { id: "03", number: "III", title: "数学预备知识", content: "books/shannon-mathematical-theory-1948/chapter-03.json" },
      { id: "04", number: "IV", title: "连续信道", content: "books/shannon-mathematical-theory-1948/chapter-04.json" },
      { id: "05", number: "V", title: "连续信源的速率", content: "books/shannon-mathematical-theory-1948/chapter-05.json" },
      { id: "a5-a7", number: "附录", title: "5—7", content: "books/shannon-mathematical-theory-1948/chapter-a5-a7.json" },
    ],
  },
];
